### ISSUE TITLE
Fact suggestion

### ISSUE THREAD

**Issue by Spheniscine** [diksown/touristfacts#66]
Tourist never needs a plumber. He just runs the max-flow algorithm on it.
Tourist can code a deterministic quicksort with no quadratic cases.
Tourist used FFT to multiply numbers in grade school.
Tourist never gets the Memory Limit Exceeded verdict, as his submissions use his own brain for storage space.
Tourist can divide by zero.
Tourist always computes the full answer for combinatorial problems before reducing it by modulo.

**Comment by ftiasch** [comment]
>  Tourist can code a deterministic quicksort with no quadratic cases.

Actually, all of us can find the median in $O(n)$ deterministically, yielding a strict $O(n \log n)$ quick sort. See https://en.wikipedia.org/wiki/Median_of_medians. 

In my opinion, there is no need to state tourist can do it to explicitly. I suggest to withdraw such fact.

**Comment by Spheniscine** [comment]
Yeah that's true. Someone did point that out to me but it was added before I could remove it from my suggestions
