### ISSUE TITLE
Fact suggestion

### ISSUE THREAD

**Issue by SecondThread** [diksown/touristfacts#67]
Tourist solves interactive problems. Offline.
The only thing tourist doesn't know is what it feels like to press the backspace key.
When tourist is bored, he occasionally solves the problems from hardest to easiest. And once he's done that, sometimes he reads the problem statements too.
Tourist is rainboy's alt.
Tourist's code doesn't even need a first thread to run in time; it simply compiles itself into the correct output using preprocessor commands.
They used to call him the traveling salesman. Now they just call him 'tourist'.

**Comment by SecondThread** [comment]
@diksown I've updated it to remove the last line. Does this work?

**Comment by diksown** [comment]
It does :100:
